CREATE TABLE users (
    id UUID PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    nickname VARCHAR NOT NULL,
    password_hash BYTEA,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
